name: Build EXE

on:
  push:
    branches:
      - main  # 触发工作流的分支

jobs:
  build:
    runs-on: windows-latest  # 在Windows环境下运行

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # 检出代码仓库

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # 选择Python版本

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller  # 安装PyInstaller

    - name: Build EXE
      run: |
        pyinstaller --onefile dabao.py  # 替换为你的脚本名称
      shell: cmd

    - name: Upload EXE
      uses: actions/upload-artifact@v3
      with:
        name: my_exe
        path: dist/dabao.exe  # 替换为生成的.exe文件路径
